# Generated by Django 5.1.7 on 2025-05-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_verified',
        ),
    ]
