# Generated by Django 5.1.7 on 2025-05-30 18:01

import django.core.validators
import venues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=255)),
                ('artist_tier', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional'), ('headliner', 'Headliner')], help_text='Required tier for artists to book this event', max_length=20)),
                ('flyer_image', models.ImageField(help_text='Background image/flyer for the event', upload_to=venues.models.event_flyer_path)),
                ('max_artists', models.PositiveIntegerField(help_text='Maximum number of artists that can be booked', validators=[django.core.validators.MinValueValidator(1)])),
                ('ticket_price', models.DecimalField(decimal_places=2, help_text='Price per ticket', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_tickets', models.PositiveIntegerField(help_text='Maximum number of tickets available', validators=[django.core.validators.MinValueValidator(1)])),
                ('venue_fee', models.DecimalField(decimal_places=2, help_text='Fee charged by the venue', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('booking_start', models.DateTimeField(help_text='Date and time when booking starts')),
                ('booking_end', models.DateTimeField(help_text='Date and time when booking ends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
