# Generated by Django 5.1.7 on 2025-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artist_tier',
            field=models.CharField(choices=[('fresh_talent', 'Fresh Talent'), ('new_blood', 'New Blood'), ('up_and_coming', 'Up and Coming'), ('rising_star', 'Rising Star'), ('scene_king', 'Scene King'), ('rockstar', 'Rockstar'), ('goliath', 'Goliath')], help_text='Required tier for artists to book this event', max_length=20),
        ),
    ]
