# Generated by Django 5.1.8 on 2025-05-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_notifications', '0003_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
    ]
