# Generated by Django 5.1.7 on 2025-06-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_notifications', '0004_remove_notification_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalEmail',
        ),
    ]
