# Generated by Django 5.1.7 on 2025-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_reciever_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], max_length=20),
        ),
    ]
