# Generated by Django 5.1.7 on 2025-03-24 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_docs', models.FileField(blank=True, null=True, upload_to='artist_verification_docs')),
                ('performance_tier', models.CharField(choices=[('fresh_talent', 'Fresh Talent'), ('new_blood', 'New Blood'), ('up_and_coming', 'Up and Coming'), ('rising_star', 'Rising Star'), ('scene_king', 'Scene King'), ('rockstar', 'Rockstar'), ('goliath', 'Goliath')], default='fresh_talent', max_length=255)),
                ('buzz_score', models.IntegerField(default=0)),
                ('onFireStatus', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
