# Generated by Django 5.1.7 on 2025-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
