# Generated by Django 5.1.7 on 2025-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_user_email_verfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
