# Generated by Django 5.1.7 on 2025-04-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0009_artist_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='band_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='band_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('essential', 'Essential'), ('pro', 'Pro'), ('elite', 'Elite')], default='starter', max_length=255),
        ),
    ]
