# Generated by Django 5.1.7 on 2025-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0010_artist_band_email_artist_band_name_artist_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='subscription_tier',
        ),
        migrations.AddField(
            model_name='artist',
            name='active_collaborations',
            field=models.ManyToManyField(to='custom_auth.artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='shows_created',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
