# Generated by Django 5.1.7 on 2025-04-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_remove_artist_subscription_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('essential', 'Essential'), ('pro', 'Pro'), ('elite', 'Elite')], default='starter', max_length=255),
        ),
    ]
