# Generated by Django 5.1.7 on 2025-04-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0012_artist_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='soundschart_uuid',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
