# Generated by Django 5.1.7 on 2025-04-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0013_artist_soundschart_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='soundschart_uuid',
            new_name='soundcharts_uuid',
        ),
    ]
