# Generated by Django 5.1.7 on 2025-04-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0014_rename_soundschart_uuid_artist_soundcharts_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_pin',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_pin_expires_in',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
