# Generated by Django 5.1.7 on 2025-04-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0015_user_contract_pin_user_contract_pin_expires_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
