# Generated by Django 5.1.7 on 2025-04-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0016_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verfied',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='artist',
            name='connections',
            field=models.ManyToManyField(related_name='artist_connections', to='custom_auth.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='active_collaborations',
            field=models.ManyToManyField(related_name='collaborators', to='custom_auth.artist'),
        ),
    ]
