# Generated by Django 5.1.7 on 2025-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_rename_email_verfied_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='artist_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='reservation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venue',
            name='seating_plan',
            field=models.ImageField(blank=True, null=True, upload_to='venue_seating_plan'),
        ),
    ]
