# Generated by Django 5.1.7 on 2025-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0018_venue_artist_capacity_venue_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='stripe_account_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='stripe_account_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
