# Generated by Django 5.1.8 on 2025-05-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0021_fan_country_fan_email_fan_full_name_fan_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='vanue_email',
            new_name='venue_email',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='vanue_location',
            new_name='venue_location',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='vanue_name',
            new_name='venue_name',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='vanue_phone',
            new_name='venue_phone',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='vanue_seating_blueprint',
            new_name='venue_seating_blueprint',
        ),
    ]
