# Generated by Django 5.1.8 on 2025-05-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0022_rename_vanue_email_venue_venue_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='venue_location',
        ),
    ]
