# Generated by Django 5.1.8 on 2025-05-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0023_remove_venue_venue_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='country',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='fan',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_email',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_phone',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_seating_blueprint',
        ),
    ]
