# Generated by Django 5.1.8 on 2025-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0024_remove_artist_personal_email_remove_fan_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
