# Generated by Django 5.1.8 on 2025-05-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0025_venue_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='adress',
            new_name='address',
        ),
    ]
