# Generated by Django 5.1.7 on 2025-06-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0026_rename_adress_venue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='venue_logos/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
