# Generated by Django 5.1.7 on 2025-06-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0026_rename_adress_venue_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('CLASS_IA', 'Class I-A (Small Local Venues)'), ('CLASS_IIA', 'Class II-A (Mid-Sized Growth Venues)'), ('CLASS_IIIA', 'Class III-A (Regional Venues)'), ('CLASS_IVA', 'Class IV-A (Major Music Halls & Theaters)'), ('CLASS_VA', 'Class V-A (Premier National Venues)'), ('CLASS_VIA', 'Class VI-A (Stadiums & Arenas)')], max_length=50, unique=True)),
                ('min_capacity', models.PositiveIntegerField(help_text='Minimum capacity for this venue tier')),
                ('max_capacity', models.PositiveIntegerField(help_text='Maximum capacity for this venue tier')),
                ('eligible_artist_tiers', models.JSONField(default=list, help_text='List of artist tiers that can perform at this venue')),
                ('description', models.TextField(blank=True, help_text='Description of the venue tier')),
                ('example_venues', models.TextField(help_text='Example venues that fall into this tier')),
            ],
            options={
                'verbose_name': 'Venue Tier',
                'verbose_name_plural': 'Venue Tiers',
                'ordering': ['min_capacity'],
            },
        ),
        migrations.AlterField(
            model_name='artist',
            name='performance_tier',
            field=models.CharField(choices=[('fresh_talent', 'Fresh Talent (0-1k followers)'), ('new_blood', 'New Blood (1k-10k followers)'), ('up_and_coming', 'Up and Coming (10k-50k followers)'), ('rising_star', 'Rising Star (50k-200k followers)'), ('scene_king', 'Scene King (200k-500k followers)'), ('rockstar', 'Rockstar (500k-1M followers)'), ('goliath', 'Goliath (1M+ followers)')], default='fresh_talent', max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Automatically set based on capacity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='custom_auth.venuetier'),
        ),
    ]
