# Generated by Django 5.1.7 on 2025-06-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0027_venuetier_alter_artist_performance_tier_venue_tier'),
    ]

    operations = [
    ]
