# Generated by Django 5.1.7 on 2025-06-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0027_venue_city_venue_logo_venue_phone_number_venue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='venue_proofs/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='proof_type',
            field=models.CharField(blank=True, choices=[('DOCUMENT', 'Document'), ('URL', 'URL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='proof_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
