# Generated by Django 5.1.7 on 2025-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0029_alter_artist_options_artist_followers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_metrics_update',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='monthly_listeners',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='total_streams',
        ),
        migrations.AddField(
            model_name='artist',
            name='last_tier_update',
            field=models.DateTimeField(blank=True, help_text='When the tier was last updated from SoundCharts', null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='soundcharts_uuid',
            field=models.CharField(blank=True, default=None, help_text='SoundCharts artist UUID for fetching tier information', max_length=255, null=True, unique=True),
        ),
    ]
