# Generated by Django 5.1.7 on 2025-06-10 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0030_alter_artist_options_remove_artist_followers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venue', 'verbose_name_plural': 'Venues'},
        ),
        migrations.AddField(
            model_name='artist',
            name='follower_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of followers from SoundCharts'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='active_collaborations',
            field=models.ManyToManyField(blank=True, help_text='Other artists this artist is collaborating with', related_name='collaborators', to='custom_auth.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='band_email',
            field=models.EmailField(blank=True, help_text='Professional email for booking inquiries', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='band_name',
            field=models.CharField(blank=True, help_text='Stage name or band name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='buzz_score',
            field=models.IntegerField(default=0, help_text="Artist's buzz score for trending"),
        ),
        migrations.AlterField(
            model_name='artist',
            name='city',
            field=models.CharField(blank=True, help_text='Base city of the artist', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='connections',
            field=models.ManyToManyField(blank=True, help_text='Network connections with other artists/industry', related_name='artist_connections', to='custom_auth.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='full_name',
            field=models.CharField(blank=True, help_text="Artist's full legal name", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='logo',
            field=models.ImageField(blank=True, help_text="Artist's profile image/logo", null=True, upload_to='artist_logo'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='onFireStatus',
            field=models.BooleanField(default=False, help_text='Whether the artist is currently trending'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='performance_tier',
            field=models.CharField(choices=[('fresh_talent', 'Fresh Talent (0-1k)'), ('new_blood', 'New Blood (1k-10k)'), ('up_and_coming', 'Up and Coming (10k-50k)'), ('rising_star', 'Rising Star (50k-200k)'), ('scene_king', 'Scene King (200k-500k)'), ('rockstar', 'Rockstar (500k-2M)'), ('goliath', 'Goliath (2M+)')], default='fresh_talent', help_text="Artist's performance tier based on follower count", max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number with country code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='shows_created',
            field=models.PositiveIntegerField(default=0, help_text='Number of shows created by this artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='state',
            field=models.CharField(blank=True, help_text='State/Region of the artist', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stripe_account_id',
            field=models.CharField(blank=True, default=None, help_text='Stripe Connect account ID for payments', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether Stripe onboarding is completed'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('essential', 'Essential'), ('pro', 'Pro'), ('elite', 'Elite')], default='starter', help_text='Subscription level for premium features', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(help_text='The user account associated with this artist', on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artist',
            name='verification_docs',
            field=models.FileField(blank=True, help_text='Upload any verification documents required', null=True, upload_to='artist_verification_docs'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the venue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(default=list, help_text='List of amenities available at the venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='artist_capacity',
            field=models.IntegerField(default=0, help_text='Maximum number of artists that can perform at the venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0, help_text='Venue capacity used to determine the tier'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether the venue profile is fully set up'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='reservation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base reservation fee for the venue', max_digits=10),
        ),
        migrations.AlterField(
            model_name='venue',
            name='seating_plan',
            field=models.ImageField(blank=True, help_text='Upload a seating plan for the venue', null=True, upload_to='venue_seating_plan'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='stripe_account_id',
            field=models.CharField(blank=True, default=None, help_text='Stripe Connect account ID for payments', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether Stripe onboarding is completed'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Venue tier based on capacity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.venuetier'),
        ),
        migrations.AlterField(
            model_name='venuetier',
            name='tier',
            field=models.CharField(choices=[('CLASS_IA', 'Class I-A (Small Local Venues)'), ('CLASS_IIA', 'Class II-A (Mid-Sized Growth Venues)'), ('CLASS_IIIA', 'Class III-A (Regional Venues)'), ('CLASS_IVA', 'Class IV-A (Major Music Halls & Theaters)'), ('CLASS_VA', 'Class V-A (Premier National Venues)'), ('CLASS_VIA', 'Class VI-A (Stadiums & Arenas)')], help_text='The classification tier of the venue', max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['performance_tier'], name='custom_auth_perform_bb766f_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['subscription_tier'], name='custom_auth_subscri_89f7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['buzz_score'], name='custom_auth_buzz_sc_f72d81_idx'),
        ),
    ]
