# Generated by Django 5.1.7 on 2025-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0031_alter_venue_options_artist_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='engagement_rate',
            field=models.FloatField(default=0.0, help_text='Engagement rate as a decimal (0-1)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of Instagram followers'),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_metrics_update',
            field=models.DateTimeField(blank=True, help_text='When the metrics were last updated', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='playlist_views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of playlist views'),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of Spotify followers'),
        ),
        migrations.AddField(
            model_name='artist',
            name='tiktok_followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of TikTok followers'),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_subscribers',
            field=models.PositiveIntegerField(default=0, help_text='Number of YouTube subscribers'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='buzz_score',
            field=models.IntegerField(default=0, help_text="Artist's buzz score (0-500)"),
        ),
    ]
