# Generated by Django 5.1.7 on 2025-06-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0028_venue_proof_document_venue_proof_type_and_more'),
        ('custom_auth', '0031_alter_venue_options_artist_follower_count_and_more'),
    ]

    operations = [
    ]
