# Generated by Django 5.1.7 on 2025-06-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0032_artist_engagement_rate_artist_instagram_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for payment processing', max_length=255, null=True),
        ),
    ]
