# Generated by Django 5.1.7 on 2025-06-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0028_venue_proof_document_venue_proof_type_and_more'),
        ('custom_auth', '0033_user_stripe_customer_id'),
    ]

    operations = [
    ]
