# Generated by Django 5.1.7 on 2025-06-23 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0033_remove_venue_tier_alter_artist_subscription_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
