# Generated by Django 5.1.7 on 2025-06-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0034_merge_20250618_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='tier',
        ),
        migrations.AddField(
            model_name='artist',
            name='monthly_listeners',
            field=models.PositiveIntegerField(default=0, help_text='Number of monthly listeners on streaming platforms'),
        ),
        migrations.AddField(
            model_name='artist',
            name='streams',
            field=models.BigIntegerField(default=0, help_text='Total number of streams across all platforms'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArtistMonthlyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month these metrics represent')),
                ('monthly_listeners', models.PositiveIntegerField(default=0)),
                ('streams', models.PositiveIntegerField(default=0)),
                ('instagram_followers', models.PositiveIntegerField(default=0)),
                ('tiktok_followers', models.PositiveIntegerField(default=0)),
                ('spotify_followers', models.PositiveIntegerField(default=0)),
                ('youtube_subscribers', models.PositiveIntegerField(default=0)),
                ('playlist_views', models.PositiveIntegerField(default=0)),
                ('fan_engagement_rate', models.DecimalField(decimal_places=2, default=0, help_text='Fan engagement rate as a percentage (0-100)', max_digits=5)),
                ('social_growth_rate', models.DecimalField(decimal_places=2, default=0, help_text='Social media following growth rate as a percentage', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_metrics', to='custom_auth.artist')),
            ],
            options={
                'verbose_name_plural': 'Artist Monthly Metrics',
                'ordering': ['-month'],
                'unique_together': {('artist', 'month')},
            },
        ),
    ]
