# Generated by Django 5.1.7 on 2025-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0035_remove_user_stripe_customer_id_remove_venue_tier_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artist',
            name='custom_auth_buzz_sc_f72d81_idx',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='buzz_score',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='engagement_rate',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='fan_engagement_rate',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='instagram_followers',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='monthly_listeners',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='playlist_views',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='social_growth_rate',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='spotify_followers',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='streams',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='tiktok_followers',
        ),
        migrations.RemoveField(
            model_name='artistmonthlymetrics',
            name='youtube_subscribers',
        ),
        migrations.AddField(
            model_name='artist',
            name='buzz_score_pct',
            field=models.FloatField(default=0.0, help_text='Buzz score as a percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='fan_engagement_pct',
            field=models.FloatField(default=0.0, help_text='Fan engagement as a percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='playlist_views_pct',
            field=models.FloatField(default=0.0, help_text='Playlist views as a percentage of max possible (0-100)'),
        ),
        migrations.AddField(
            model_name='artist',
            name='social_following_pct',
            field=models.FloatField(default=0.0, help_text='Social media following as a percentage of max possible (0-100)'),
        ),
        migrations.AddField(
            model_name='artistmonthlymetrics',
            name='buzz_score_pct',
            field=models.FloatField(default=0.0, help_text='Buzz score as a percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='artistmonthlymetrics',
            name='fan_engagement_pct',
            field=models.FloatField(default=0.0, help_text='Fan engagement as a percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='artistmonthlymetrics',
            name='playlist_views_pct',
            field=models.FloatField(default=0.0, help_text='Playlist views as a percentage of max possible (0-100)'),
        ),
        migrations.AddField(
            model_name='artistmonthlymetrics',
            name='social_following_pct',
            field=models.FloatField(default=0.0, help_text='Social media following as a percentage of max possible (0-100)'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['buzz_score_pct'], name='custom_auth_buzz_sc_f2bfb3_idx'),
        ),
        migrations.AddIndex(
            model_name='artistmonthlymetrics',
            index=models.Index(fields=['month'], name='custom_auth_month_e6295d_idx'),
        ),
        migrations.AddIndex(
            model_name='artistmonthlymetrics',
            index=models.Index(fields=['artist', 'month'], name='custom_auth_artist__c5cffc_idx'),
        ),
    ]
