# Generated by Django 5.1.7 on 2025-06-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0034_artist_likes'),
        ('custom_auth', '0036_remove_artist_custom_auth_buzz_sc_f72d81_idx_and_more'),
    ]

    operations = [
    ]
