# Generated by Django 5.1.7 on 2025-06-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0033_fix_venue_tier_removal'),
        ('custom_auth', '0037_merge_20250624_2134'),
    ]

    operations = [
    ]
