# Generated by Django 5.1.7 on 2025-06-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0038_merge_20250624_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='tier',
            field=models.ForeignKey(blank=True, help_text="The venue's performance tier based on capacity", null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.venuetier'),
        ),
    ]
