# Generated by Django 5.1.7 on 2025-07-07 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0041_alter_venue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
