# Generated by Django 5.1.7 on 2025-07-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0042_alter_venue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='stripe_onboarding_link',
            field=models.URLField(blank=True, help_text='Latest Stripe onboarding link for this venue', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='stripe_onboarding_link',
            field=models.URLField(blank=True, help_text='Latest Stripe onboarding link for this venue', null=True),
        ),
    ]
