# Generated by Django 5.1.7 on 2025-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0043_artist_stripe_onboarding_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='merch_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
