# Generated by Django 5.1.7 on 2025-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0044_artist_merch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
