# Generated by Django 5.1.7 on 2025-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0045_artist_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='End date of the current subscription period', null=True),
        ),
    ]
