# Generated by Django 5.1.7 on 2025-06-03 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0026_rename_adress_venue_address'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAdPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STARTER', 'Starter'), ('BOOSTED', 'Boosted'), ('PREMIUM', 'Premium')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('weekly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekly_stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('features', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='VenueSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=100)),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True)),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], default='incomplete', max_length=20)),
                ('billing_interval', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly')], default='month', max_length=10)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.venueadplan')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_subscriptions', to='custom_auth.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
