# Generated by Django 5.1.7 on 2025-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_venueadplan_alter_subscriptionplan_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], max_length=255),
        ),
    ]
