# Generated by Django 5.1.7 on 2025-07-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionplan_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuesubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan'),
        ),
    ]
