# Generated by Django 5.1.7 on 2025-07-08 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_venuesubscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='venue_ad_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.venueadplan'),
        ),
    ]
