# Generated by Django 5.1.7 on 2025-07-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptionplan_venue_ad_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
