# Generated by Django 5.1.7 on 2025-07-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_artistsubscription_current_period_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistsubscription',
            name='current_period_start',
        ),
    ]
