# Generated by Django 5.1.7 on 2025-04-04 12:41

import django.utils.timezone
import gigs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='eventEndDate',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='gig',
            name='eventStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
