# Generated by Django 5.1.7 on 2025-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_eventenddate_gig_eventstartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
