# Generated by Django 5.1.7 on 2025-04-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_seatrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='gigs.seatrow'),
        ),
        migrations.AlterField(
            model_name='seatrow',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='gigs.gig'),
        ),
    ]
