# Generated by Django 5.1.7 on 2025-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_application_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
