# Generated by Django 5.1.7 on 2025-04-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_remove_gig_venue_gig_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='recipient_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_signed',
            field=models.BooleanField(default=False),
        ),
    ]
