# Generated by Django 5.1.7 on 2025-04-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0015_user_contract_pin_user_contract_pin_expires_in'),
        ('gigs', '0010_contract_recipient_signed_contract_user_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.AddField(
            model_name='contract',
            name='artist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='custom_auth.artist'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='gigs/contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='venue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='custom_auth.venue'),
        ),
    ]
