# Generated by Django 5.1.7 on 2025-04-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0011_remove_contract_recipient_remove_contract_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='recipient_signed',
            new_name='artist_signed',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='user_signed',
            new_name='venue_signed',
        ),
    ]
