# Generated by Django 5.1.7 on 2025-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0012_rename_recipient_signed_contract_artist_signed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={},
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='endDate',
            new_name='booking_end_date',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='startDate',
            new_name='booking_start_date',
        ),
        migrations.RenameField(
            model_name='gig',
            old_name='eventStartDate',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='eventEndDate',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='flyer_text',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='gig',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='seatrow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seatrow',
            name='gig',
        ),
        migrations.RemoveField(
            model_name='seatrow',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seatrow',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gig',
            name='genre',
            field=models.CharField(choices=[('rap', 'Rap'), ('hip_hop', 'Hip Hop'), ('pop', 'Pop')], default='rap', max_length=255),
        ),
        migrations.AddField(
            model_name='gig',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gig',
            name='max_tickets',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gig',
            name='minimum_performance_tier',
            field=models.CharField(choices=[('fresh_talent', 'Fresh Talent'), ('new_blood', 'New Blood'), ('up_and_coming', 'Up and Coming'), ('rising_star', 'Rising Star'), ('scene_king', 'Scene King'), ('rockstar', 'Rockstar'), ('goliath', 'Goliath')], default='fresh_talent', max_length=255),
        ),
        migrations.AddField(
            model_name='gig',
            name='request_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
