# Generated by Django 5.1.7 on 2025-05-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0013_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='max_tickets',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gig',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
