# Generated by Django 5.1.7 on 2025-05-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0014_alter_gig_max_tickets_alter_gig_ticket_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='SeatRow',
        ),
    ]
