# Generated by Django 5.1.7 on 2025-05-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0017_rename_email_verfied_user_email_verified_and_more'),
        ('gigs', '0015_delete_seat_delete_seatrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='venue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='custom_auth.venue'),
        ),
    ]
