# Generated by Django 5.1.7 on 2025-05-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0016_gig_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
