# Generated by Django 5.1.7 on 2025-05-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0017_gig_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='price',
        ),
    ]
