# Generated by Django 5.1.7 on 2025-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0018_remove_contract_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
