# Generated by Django 5.1.7 on 2025-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0019_contract_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
    ]
