# Generated by Django 5.1.7 on 2025-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0018_venue_artist_capacity_venue_is_completed_and_more'),
        ('gigs', '0020_remove_gig_is_approved_gig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='invitees',
            field=models.ManyToManyField(blank=True, related_name='invited_gigs', to='custom_auth.artist'),
        ),
    ]
