# Generated by Django 5.1.7 on 2025-05-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0018_venue_artist_capacity_venue_is_completed_and_more'),
        ('gigs', '0021_gig_invitees'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_invites_sent', to='custom_auth.artist')),
                ('artist_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_invites_received', to='custom_auth.artist')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.gig')),
            ],
        ),
    ]
