# Generated by Django 5.1.7 on 2025-05-07 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0022_giginvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giginvite',
            name='artist',
        ),
        migrations.AddField(
            model_name='giginvite',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
