# Generated by Django 5.1.7 on 2025-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0023_remove_giginvite_artist_giginvite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
