# Generated by Django 5.1.7 on 2025-05-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0024_gig_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
