# Generated by Django 5.1.7 on 2025-05-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0019_artist_stripe_account_id_and_more'),
        ('gigs', '0025_contract_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_gigs', to='custom_auth.artist'),
        ),
    ]
