# Generated by Django 5.1.7 on 2025-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0027_gig_slot_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='venue_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
