# Generated by Django 5.1.7 on 2025-05-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0028_gig_venue_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='booking_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='booking_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
