# Generated by Django 5.1.7 on 2025-06-05 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0030_remove_gig_flyer_bg_remove_gig_genre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Artists who are collaborating on this gig', related_name='collaborated_gigs_artist', to=settings.AUTH_USER_MODEL),
        ),
    ]
