# Generated by Django 5.1.7 on 2025-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0031_alter_gig_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title of the gig/event', max_length=255),
        ),
    ]
