# Generated by Django 5.1.7 on 2025-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0031_alter_gig_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='minimum_performance_tier',
            field=models.CharField(blank=True, choices=[('fresh_talent', 'Fresh Talent (0-1k followers)'), ('new_blood', 'New Blood (1k-10k followers)'), ('up_and_coming', 'Up and Coming (10k-50k followers)'), ('rising_star', 'Rising Star (50k-200k followers)'), ('scene_king', 'Scene King (200k-500k followers)'), ('rockstar', 'Rockstar (500k-1M followers)'), ('goliath', 'Goliath (1M+ followers)')], default='fresh_talent', help_text='Minimum performance tier required for artists', max_length=255, null=True),
        ),
    ]
