# Generated by Django 5.1.7 on 2025-06-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0030_alter_artist_options_remove_artist_followers_and_more'),
        ('gigs', '0032_alter_gig_minimum_performance_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='is_part_of_tour',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this gig is part of a tour'),
        ),
        migrations.AddField(
            model_name='gig',
            name='tour_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The order of this gig in the tour sequence', null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='gig_type',
            field=models.CharField(choices=[('artist_gig', 'Artist Gig'), ('venue_gig', 'Venue Gig'), ('tour_gig', 'Tour Gig')], default='artist_gig', help_text='Type of gig (artist-created or venue-created)', max_length=20),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Name of the tour', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(help_text='Tour start date')),
                ('end_date', models.DateField(help_text='Tour end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('announced', 'Announced'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the tour', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this tour is featured on the platform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(help_text='The artist/band going on tour', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='custom_auth.artist')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='gig',
            name='tour',
            field=models.ForeignKey(blank=True, help_text='The tour this gig belongs to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gigs', to='gigs.tour'),
        ),
    ]
