# Generated by Django 5.1.7 on 2025-06-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0033_gig_is_part_of_tour_gig_tour_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='minimum_performance_tier',
            field=models.CharField(blank=True, choices=[('fresh_talent', 'Fresh Talent (0-1k)'), ('new_blood', 'New Blood (1k-10k)'), ('up_and_coming', 'Up and Coming (10k-50k)'), ('rising_star', 'Rising Star (50k-200k)'), ('scene_king', 'Scene King (200k-500k)'), ('rockstar', 'Rockstar (500k-2M)'), ('goliath', 'Goliath (2M+)')], default='fresh_talent', help_text='Minimum performance tier required for artists', max_length=255, null=True),
        ),
    ]
