# Generated by Django 5.1.7 on 2025-06-12 16:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0031_alter_venue_options_artist_follower_count_and_more'),
        ('gigs', '0034_alter_gig_minimum_performance_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='driving_range_km',
            field=models.PositiveIntegerField(default=100, help_text='Maximum driving distance in kilometers between tour stops', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tour',
            name='selected_cities',
            field=models.JSONField(default=list, help_text='List of city names selected for the tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='selected_states',
            field=models.JSONField(default=list, help_text='List of state names selected for the tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('bus', 'Bus'), ('flight', 'Flight'), ('train', 'Train'), ('other', 'Other')], default='car', help_text='Type of vehicle for travel between cities', max_length=20),
        ),
        migrations.CreateModel(
            name='TourVenueSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=django.utils.timezone.now, help_text='Scheduled date for the show at this venue')),
                ('is_booked', models.BooleanField(default=False, help_text='Whether this venue has been booked for the tour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(help_text='The tour this suggestion is for', on_delete=django.db.models.deletion.CASCADE, related_name='suggested_venues', to='gigs.tour')),
                ('venue', models.ForeignKey(help_text='The suggested venue', on_delete=django.db.models.deletion.CASCADE, related_name='tour_suggestions', to='custom_auth.venue')),
            ],
            options={
                'verbose_name': 'Tour Venue Suggestion',
                'verbose_name_plural': 'Tour Venue Suggestions',
                'ordering': ['tour', 'event_date'],
                'unique_together': {('tour', 'venue')},
            },
        ),
    ]
