# Generated by Django 5.1.7 on 2025-06-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0033_alter_gig_ticket_price'),
        ('gigs', '0035_tour_driving_range_km_tour_selected_cities_and_more'),
    ]

    operations = [
    ]
