# Generated by Django 5.1.7 on 2025-06-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0036_merge_20250618_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='genre',
            field=models.CharField(blank=True, choices=[('rap', 'Rap'), ('hip_hop', 'Hip Hop'), ('pop', 'Pop')], default='rap', help_text='Genre of the gig', max_length=20, null=True),
        ),
    ]
