# Generated by Django 5.1.7 on 2025-06-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0036_merge_20250618_1851'),
        ('gigs', '0037_gig_genre'),
    ]

    operations = [
    ]
