# Generated by Django 5.1.7 on 2025-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0038_merge_0036_merge_20250618_1851_0037_gig_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(blank=True, help_text='Tour end date', null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(blank=True, help_text='Tour start date', null=True),
        ),
    ]
