# Generated by Django 5.1.7 on 2025-07-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0039_alter_tour_end_date_alter_tour_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(blank=True, help_text='Name of the tour', max_length=255, null=True),
        ),
    ]
