# Generated by Django 5.1.7 on 2025-07-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0040_alter_tour_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourvenuesuggestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
