# Generated by Django 5.1.7 on 2025-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0041_tourvenuesuggestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='artist_tier',
            field=models.CharField(blank=True, choices=[('fresh_talent', 'Fresh Talent (0-1k)'), ('new_blood', 'New Blood (1k-10k)'), ('up_and_coming', 'Up and Coming (10k-50k)'), ('rising_star', 'Rising Star (50k-200k)'), ('scene_king', 'Scene King (200k-500k)'), ('rockstar', 'Rockstar (500k-2M)'), ('goliath', 'Goliath (2M+)')], max_length=50, null=True),
        ),
    ]
