# Generated by Django 5.1.7 on 2025-07-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0042_gig_artist_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='artist_tier',
        ),
    ]
