# Generated by Django 5.1.7 on 2025-07-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0043_remove_gig_artist_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('timed_out', 'Timed Out')], default='pending', help_text='Current status of the gig', max_length=20),
        ),
    ]
